name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workload_dispatch:
    inputs:
     reason:
      description: "Reason for manual trigger"
      required: false
      default: "Test run"
      type: string
  schedule:
    - cron: "0 0 * * 0" #weekly on sundays at midnight

#Related to github pages
permissions:
  content: read
  pages: write
  id-token: write

concurrences:
  group: "pages"
  cancel-in-progress: false

jobs:
  #CI job - Run tests and linting
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      -name: checkout code
      uses: actions/checkout@v6 #uses hye la n3ayet lal action with options

      -name: setup Node-js
      uses: actions/setup-node@v6
      with:
        node-versions: "24"
        cache: "npm"

      -name: install dependencies
      run: npm ci 

      -name: run linter
      run: npm run lint

      -name: check formatting
      run: npm run format:check

      -name: Run tests
      run: npm test

      -name: Build project #first artifact 
      run: npm run Build

      -name: Generate simple log
      run: mkdir -p logs
           echo "CI Pipeline run at $(date)" > logs/pipeline.log
           echo "Tests passed" >>logs/pipeline.log

      -name: Generate demo HTML page
      run: mkdir -p public 
           cp demo/index.html public/
           cp dist/sum.js public/

      -name: Upload build logs artifact
      uses: actions/upload-artifact@v6
      with:
          name: build-logs
          path: logs/
          retention-days: 30

      -name: Upload demo site artifact
      uses: actions/upload-artifact@v6
      with:
          name: demo-site
          path: public/
          retention-days: 30

      deploy:
        name: Deploy to GitHub Pages
        needs: ci
        runs-on: ubuntu-latest

        # Only deploy on push to main branch
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'

        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}

        steps:
          -name: Download artifact
          uses: actions/download-artifact@v7
          with:
              name: demo-site
              path: ./public

          -name: Upload to GitHub Pages
          uses: actions/upload-pages-artifact@v3
          with:
              path: ./public

          -name: Deploy to GitHub Pages
          id: deployment
          uses: actions/deploy-pages@v4



